name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: patch
        run: |
          cd src

          ./check_verilog_timerconsts.sh || true

          echo "### Temporary patch remove before production and signoff"
          echo "### For local simulation these timers values are 1/200th or 1/25th of the normal wall-clock time"
          echo "### This patch restores the production values to meet USB specification with a 48MHz PHY clock source"

          ./check_verilog_timerconsts.sh patch quiet

          echo ""
          echo "### This now validates the values inside verilog are production system values or halts the CI"

          ./check_verilog_timerconsts.sh

      - name: Run tests
        run: |
          iverilog -V 2>&1 | head -n1 || true
          cd test

          make clean
          rm -f results.xml

          make
          test -f results.xml

          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/tb.vcd
            test/results.xml
